### ISSUE TITLE
Bash receiving exit code 2 instead of number provided to exit function

### ISSUE THREAD

**Issue by Glen-Moonpig** [oclif/errors#67]
I am using Apollo GraphQL CLI, which uses this package.

Under a certain error scenario the Apollo CLI calls exit with value 1.

```
this.exit(1);
```

The exit function above is from the Command class imported from "@oclif/command";

In bash I always receive exit code 2.

```bash
(
  set -Ee
  function _catch {
    APOLLO_EXIT_CODE=$1
    echo "Apollo CLI exited with code $APOLLO_EXIT_CODE"
  }
  trap '_catch $?' ERR
  apollo service:push
)
```

or more simply..

```bash
apollo service:push
echo $?
```
The bin/run:

```
#!/usr/bin/env node

require('@oclif/command').run()
.catch(require('@oclif/errors/handle'))
```

**Comment by RasPhilCo** [comment]
Hmm weird! Thanks for bringing this up, will take a deeper look when we can.

**Comment by Glen-Moonpig** [comment]
I changed the bin/run file to log the error:

```
#!/usr/bin/env node

require('@oclif/command').run()
.catch(console.log)
```

The output:

```
ExitError: EEXIT: 1
    at Object.exit (/usr/local/lib/node_modules/apollo/node_modules/@oclif/errors/lib/index.js:19:11)
    at ServicePush.exit (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:54:23)
    at ServicePush.run (/usr/local/lib/node_modules/apollo/lib/commands/service/push.js:123:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ServicePush._run (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/apollo/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:43:20) {
  oclif: { exit: 2 },
  code: 'EEXIT'
}
```

**Comment by Glen-Moonpig** [comment]
I modified @oclif/errors/lib/errors/cli.js to log a trace every time addOclifExitCode is called and I can now see that the thrown ExitError is caught in Apollo CLI and then the error function is called, changing the code to 2. This is a bug in Apollo.

```
Adding oclif exit code {"exit":1} to error {"oclif":{}}
Trace
    at addOclifExitCode (/usr/local/lib/node_modules/apollo/node_modules/@oclif/errors/lib/errors/cli.js:7:13)
    at new CLIError (/usr/local/lib/node_modules/apollo/node_modules/@oclif/errors/lib/errors/cli.js:19:9)
    at new ExitError (/usr/local/lib/node_modules/apollo/node_modules/@oclif/errors/lib/errors/exit.js:6:9)
    at Object.exit (/usr/local/lib/node_modules/apollo/node_modules/@oclif/errors/lib/index.js:20:11)
    at ServicePush.exit (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:54:23)
    at ServicePush.run (/usr/local/lib/node_modules/apollo/lib/commands/service/push.js:123:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ServicePush._run (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/apollo/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/main.js:22:9)
Adding oclif exit code {} to error {"oclif":{"exit":1},"code":"EEXIT"}
Trace
    at Object.addOclifExitCode (/usr/local/lib/node_modules/apollo/node_modules/@oclif/errors/lib/errors/cli.js:7:13)
    at Object.error (/usr/local/lib/node_modules/apollo/node_modules/@oclif/errors/lib/index.js:30:21)
    at ServicePush.error (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:60:23)
    at ServicePush.catch (/usr/local/lib/node_modules/apollo/lib/Command.js:156:14)
    at ServicePush._run (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:47:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
